#{city}, {as}, {as_name}, {country}, {region_name}
#{isp}, {lat}, {lon}, {ip}
Messages:
  - ""
  - "&6&lJLocation &7> &e{player} / {ip}"
  - "&6&lJLocation &7> &eCountry: {country}"
  - "&6&lJLocation &7> &eCity: {city}"
  - "&6&lJLocation &7> &eLat/Lon: {lat} / {lon}"
  - "&6&lJLocation &7> &eProvider: {as}"
  - "&6&lJLocation &7> &eProvider Name: {as_name}"
  - "&6&lJLocation &7> &eRegion Name: {region_name}"
  - "&6&lJLocation &7> &eISP: {isp}"
  - ""